export const VE = {
  INVALID_JSON: "INVALID_JSON",
  NOT_STRING: "NOT_STRING",
  INVALID_TYPE: "INVALID_TYPE",
  INVALID_UUID: "INVALID_UUID",

  LOGIN_INVALID: "LOGIN_INVALID",

  USERNAME_TOO_SHORT: "USERNAME_TOO_SHORT",
  USERNAME_TOO_LONG: "USERNAME_TOO_LONG",
  USERNAME_INVALID: "USERNAME_INVALID",
  
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORDS_DONT_MATCH: "PASSWORDS_DONT_MATCH",
  
  DISPLAY_NAME_TOO_SHORT: "DISPLAY_NAME_TOO_SHORT",
  DISPLAY_NAME_TOO_LONG: "DISPLAY_NAME_TOO_LONG",
  
  BIO_TOO_SHORT: "BIO_TOO_SHORT",
  BIO_TOO_LONG: "BIO_TOO_LONG",
  
  EMAIL_INVALID: "EMAIL_INVALID",

  GOOGLE_TOKEN_INVALID: "GOOGLE_TOKEN_INVALID",

} as const 

export type ValidationErrorCode = (typeof VE)[keyof typeof VE]