export const SE = {
  INVALID_GOOGLE_TOKEN: "INVALID_GOOGLE_TOKEN",
  INVALID_JWT: "INVALID_JWT",

  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  NOT_GMAIL: "NOT_GMAIL",
  NOT_JWT: "NOT_JWT",
  NOT_REFRESH_TOKEN: "NOT_REFRESH_TOKEN",
  NOT_ACCESS_TOKEN: "NOT_ACCESS_TOKEN",

  REFRESH_NOT_FOUND: "REFRESH_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  USERNAME_TAKEN: "USERNAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  USER_ALREADY_ASKED: "USER_ALREADY_ASKED",

  EMAIL_TOKEN_EXPIRED: "EMAIL_TOKEN_EXPIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

  AVATAR_COOLDOWN: "AVATAR_COOLDOWN",
  USERNAME_COOLDOWN: "USERNAME_COOLDOWN",
  MONEY_REQUEST_COOLDOWN: "MONEY_REQUEST_COOLDOWN",

  INCORRECT_EMAIL_OR_PASSWORD: "INCORRECT_EMAIL_OR_PASSWORD",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",

  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  CANNOT_TRANSFER_TO_SELF: "CANNOT_TRANSFER_TO_SELF",
  CANNOT_REQUEST_SELF: "CANNOT_REQUEST_SELF",

  SOMETHING_WRONG: "SOMETHING_WRONG",

  NOT_OWNER: "NOT_OWNER",
  NOT_ADMIN: "NOT_ADMIN",
  NOT_DEV: "NOT_DEV",

} as const;

export type ErrorCode = (typeof SE)[keyof typeof SE]